project:
  type: website
  output-dir: docs

website:
  title: "Home"
  favicon: logo.png
  navbar:
    background: primary
    right:
      - text: about me
        href: "index.qmd"
      - text: CV
        href: "posts/CV/index.qmd"
      - text: Portfolio
        href: "posts/portfolio/index.qmd"
      - icon: github
        href: https://github.com/claire-hsieh
      - icon: linkedin
        href: https://www.linkedin.com/in/claire-hsieh-539456174/
    google-analytics: "G-T7KP22J9M5"
format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full

